---
- hosts: all
  become: true
  tasks:
    - name: Wipe out existing MBR
      command: dd bs=512 count=1 if=/dev/zero of=/dev/sdb
      become: true

    - name: Load Raspbian base image
      copy:
        src: "{{raspbian_image_path}}"
        dest: /tmp/raspbian.bin

    - name: Burn Raspbian base image
      command: dd bs=4M if=/tmp/raspbian.bin of=/dev/sdb
      become: true

    - name: Mount boot partition
      mount:
        name=/raspbian-boot
        src=/dev/sdb1
        fstype=vfat
        state=mounted

    - name: Mount root partition
      mount:
        name=/raspbian-root
        src=/dev/sdb2
        fstype=ext4
        state=mounted

    - name: Configure wifi
      template:
        src: templates/wpa_supplicant.conf.j2
        dest: /raspbian-root/etc/wpa_supplicant/wpa_supplicant.conf
        mode: 0600
        owner: root
        group: root

    # Needed as of 2016-11-25 release. See:
    # * https://www.raspberrypi.org/blog/a-security-update-for-raspbian-pixel
    # * https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=166984#p1075069
    - name: Enable SSH
      file:
        path: /raspbian-boot/ssh
        state: touch

    - name: Flush the write cache
      command: sync
      become: true

    - name: Unmount the boot partition
      mount:
        name=/raspbian-boot
        state=unmounted

    - name: Unmount the root partition
      mount:
        name=/raspbian-root
        state=unmounted
